services:
  - type: web
    name: cart-recovery-api
    env: python
    plan: starter
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: cart-recovery-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: cart-recovery-redis
          property: connectionString
      - key: TWILIO_ACCOUNT_SID
        sync: false
      - key: TWILIO_AUTH_TOKEN
        sync: false
      - key: TWILIO_WHATSAPP_NUMBER
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: WEBHOOK_SECRET
        sync: false

  - type: worker
    name: cart-recovery-worker
    env: python
    plan: starter
    buildCommand: pip install -r requirements.txt
    startCommand: celery -A app.services.scheduler.celery_app worker --loglevel=info
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: cart-recovery-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: cart-recovery-redis
          property: connectionString
      - key: TWILIO_ACCOUNT_SID
        sync: false
      - key: TWILIO_AUTH_TOKEN
        sync: false
      - key: TWILIO_WHATSAPP_NUMBER
        sync: false
      - key: OPENAI_API_KEY
        sync: false

databases:
  - name: cart-recovery-db
    plan: starter

services:
  - type: redis
    name: cart-recovery-redis
    plan: starter
